src-git passwall_packages https://github.com/Openwrt-Passwall/openwrt-passwall-packages.git;main
src-git passwall_luci https://github.com/Openwrt-Passwall/openwrt-passwall.git;main
src-git passwall2_luci https://github.com/Openwrt-Passwall/openwrt-passwall.git;main

src-git packages https://github.com/immortalwrt/packages.git
src-git luci https://github.com/immortalwrt/luci.git
src-git routing https://github.com/openwrt/routing.git
src-git telephony https://github.com/openwrt/telephony.git
src-git video https://github.com/openwrt/video.git

# OpenClash
#src-git openclash https://github.com/vernesong/OpenClash.git;master

# SSR Plus+
#src-git helloworld https://github.com/fw876/helloworld.git;master

# Mihomo
#src-git mihomo https://github.com/morytyann/OpenWrt-mihomo.git;main

# Argon
#src-git argon https://github.com/jerrykuku/luci-theme-argon.git;master

# MAC Address
src-git arcma https://github.com/newadev/luci-app-arcma.git;main

